
services:

  postgres:
    image: postgres:15-alpine
    container_name: banking-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: banking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - banking-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d banking"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  spring-boot-service:
    build: ./spring-boot-service
    container_name: core-banking
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - banking-net
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped


  mongo:
    image: mongo:7-jammy
    container_name: banking-mongo
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - banking-net
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  mongo-init:
    image: mongo:7-jammy
    container_name: banking-mongo-init
    networks:
      - banking-net
    depends_on:
      mongo:
        condition: service_healthy
    entrypoint: >
      mongosh --host banking-mongo:27017 --eval
      "try { rs.status() } catch(e) { rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: 'banking-mongo:27017' }] }) }"
    restart: on-failure

  gin-service:
    build: ./gin-service
    container_name: transfer-processor
    ports:
      - "8081:8081"
    environment:
      - MONGO_URI=mongodb://banking-mongo:27017/?replicaSet=rs0
      - MONGO_DB=banking
      - SPRING_BOOT_URL=${SPRING_BOOT_URL}
      - TEMPORAL_HOST=host.docker.internal:7233
    networks:
      - banking-net
    depends_on:
      mongo:
        condition: service_healthy
      mongo-init:
        condition: service_completed_successfully
      spring-boot-service:
        condition: service_started
    restart: unless-stopped

  fastapi-service:
    build: ./fastapi-service
    container_name: fraud-analytics
    ports:
      - "8082:8082"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SPRING_BOOT_URL=${SPRING_BOOT_URL}
    networks:
      - banking-net
    restart: unless-stopped

  streamlit-service:
    build: ./streamlit-service
    container_name: banking-frontend
    ports:
      - "8501:8501"
    environment:
      - SPRING_BOOT_URL=${SPRING_BOOT_URL}
      - GIN_URL=${GIN_URL}
      - FASTAPI_URL=${FASTAPI_URL}
    networks:
      - banking-net
    depends_on:
      spring-boot-service:
        condition: service_started
      gin-service:
        condition: service_started
      fastapi-service:
        condition: service_started
    restart: unless-stopped

volumes:
  pgdata:
  mongodata:

networks:
  banking-net:
    driver: bridge